services:
  - type: web
    name: ytdlp-telegram-bot
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8592427659:AAEwOQyvgWlVhrVnpj9teRBpVFROu5Ctpoc
      - key: PORT
        value: 10000